--- 
before_install: 
  - "docker-compose up --build -d"
  - "docker login -u \"$HEROKU_USERNAME\" -p \"$HEROKU_API_KEY\" registory.heroku.com"
deploy: ~
script: "docker build -t registory.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .; docker push registory.heroku.com/$HEROKU_APP_NAME/web; heroku run --app $HEROKU_APP_NAME rails db:migrate;"
services: docker
sudo: required
true: 
  branch: master
　provider: script